---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
    - name: "Test sonic_bgp_neighbors delete all"
      sonic_bgp_neighbors:
        state: deleted

    - name: "Test sonic_bgp_neighbors delete all idempotent"
      sonic_bgp_neighbors:
        state: deleted

    - name: "Test sonic_bgp_neighbors merged state"
      sonic_bgp_neighbors:
        config:
            - bgp_as: 11
              vrf_name: VrfCheck2
              peer_group: 
                - name: SPINE
                  remote_as:
                    peer_type: internal
                  bfd: true
                  advertisement_interval: 15
                  timers:
                    keepalive: 50
                    holdtime: 40
                  capability:
                    dynamic: true
                    extended_nexthop: true
                - name: SPINE2
              neighbors: 
                - neighbor: Ethernet12
                  remote_as:
                    peer_type: internal
                  peer_group: SPINE
                  advertisement_interval: 10
                  timers:
                    keepalive: 40
                    holdtime: 50
                  bfd: true
                  capability:
                    dynamic: true
                    extended_nexthop: true
                - neighbor: 192.168.1.4
                - neighbor: Ethernet8
                  remote_as: 
                    peer_as: 3
                  peer_group: SPINE2
                  advertisement_interval: 20
                  timers:
                    keepalive: 30
                    holdtime: 20
                  capability:
                    dynamic: true
            - bgp_as: 51
              vrf_name: VrfReg1
              peer_group:
                - name: SPINE3
                  remote_as:
                    peer_type: internal
                  bfd: true
                  advertisement_interval: 15
                  timers:
                    keepalive: 50
                    holdtime: 40
                  capability:
                    dynamic: true
                    extended_nexthop: true
              neighbors:
                - neighbor: Ethernet32
        state: merged

    - name: "Test sonic_bgp_neighbors merged state idempotent"
      sonic_bgp_neighbors:
        config:
            - bgp_as: 11
              vrf_name: VrfCheck2
              peer_group:
                - name: SPINE
                  remote_as:
                    peer_type: internal
                  bfd: true
                  advertisement_interval: 15
                  timers:
                    keepalive: 50
                    holdtime: 40
                  capability:
                    dynamic: true
                    extended_nexthop: true
                - name: SPINE2
              neighbors:
                - neighbor: Ethernet12
                  remote_as:
                    peer_type: internal
                  peer_group: SPINE
                  advertisement_interval: 10
                  timers:
                    keepalive: 40
                    holdtime: 50
                  bfd: true
                  capability:
                    dynamic: true
                    extended_nexthop: true
                - neighbor: 192.168.1.4
                - neighbor: Ethernet8
                  remote_as:
                    peer_as: 3
                  peer_group: SPINE2
                  advertisement_interval: 20
                  timers:
                    keepalive: 30
                    holdtime: 20
                  capability:
                    dynamic: true
            - bgp_as: 51
              vrf_name: VrfReg1
              peer_group:
                - name: SPINE3
                  remote_as:
                    peer_type: internal
                  bfd: true
                  advertisement_interval: 15
                  timers:
                    keepalive: 50
                    holdtime: 40
                  capability:
                    dynamic: true
                    extended_nexthop: true
              neighbors:
                - neighbor: Ethernet32
        state: merged

    - name: "Test delete sonic_bgp_neighbors and peergroup vrf specific"
      sonic_bgp_neighbors:
        config:
          - bgp_as: 51
            vrf_name: VrfReg1
        state: deleted


    - name: "Test delete sonic_bgp_neighbors and peergroup vrf specific idempotent"
      sonic_bgp_neighbors:
        config:
          - bgp_as: 51
            vrf_name: VrfReg1
        state: deleted

    - name: "Test delete sonic_bgp_neighbors peergroup and neighbor attributes"
      sonic_bgp_neighbors:
        config:
          - bgp_as: 11
            vrf_name: VrfCheck2
            peer_group:
              - name: SPINE
                remote_as:
                   peer_type: internal
                bfd: true
                advertisement_interval: 15
                timers:
                  keepalive: 50
                  holdtime: 40
                capability:
                  dynamic: true
                  extended_nexthop: true
            neighbors:
              - neighbor: Ethernet12
                remote_as:
                  peer_type: internal
                peer_group: SPINE
                advertisement_interval: 30
                timers:
                  holdtime: 180
                  keepalive: 60
                capability:
                  dynamic: False
                  extended_nexthop: False
                bfd: False
              - neighbor: Ethernet8
        state: deleted
      
    - name: "Test delete sonic_bgp_neighbors peergroup and neighbor attributes idempotent"
      sonic_bgp_neighbors:
        config:
          - bgp_as: 11
            vrf_name: VrfCheck2
            peer_group:
                - name: SPINE
                  remote_as:
                    peer_type: internal
                  bfd: true
                  advertisement_interval: 15
                  timers:
                    keepalive: 50
                    holdtime: 40
                  capability:
                    dynamic: true
                    extended_nexthop: true
            neighbors:
              - neighbor: Ethernet12
                remote_as:
                  peer_type: internal
                peer_group: SPINE
                advertisement_interval: 30
                timers:
                  holdtime: 180
                  keepalive: 60
                capability:
                  dynamic: False
                  extended_nexthop: False
                bfd: False
              - neighbor: Ethernet8
        state: deleted

    - name: "Test peer-groups delete"
      sonic_bgp_neighbors:
        config:
            - bgp_as: 11
              vrf_name: VrfCheck2
              peer_group:
                - name: SPINE
                - name: SPINE2
        state: deleted

    - name: "Test peer-groups delete idempotent"
      sonic_bgp_neighbors:
        config:
            - bgp_as: 11
              vrf_name: VrfCheck2
              peer_group:
                - name: SPINE
                - name: SPINE2
        state: deleted
