---
- name: "Test SONiC CLI"
  hosts: datacenter 
  gather_facts: no
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
  - name: Add one l3 interface
    sonic_l3_interfaces:
      config:
        - name: Po100
      state: deleted
    register: merge_l3_interface_single_output
