---
- name: "Test SONiC CLI"
  hosts: sonic1
  gather_facts: no
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
  - name: Add one bgp_extcommunity
    sonic_bgp_ext_communities:
      config:
        - name: exp1
          type: expanded
          permit: true
          members:
            regex:
              - "11"
              - "22"
              - "33"
        - name: std1
          type: standard
          permit: true
          members:
            route_target:
              - "101.101"
              - "201.201"
            route_origin:
              - "301.301"
              - "401.401"
      state: merged
    register: merge_bgp_extcommunity_single_output
  - name: Add one bgp_extcommunity Idempotent test
    sonic_bgp_ext_communities:
      config:
        - name: exp1
          type: expanded
          permit: true
          members:
            regex:
              - "11"
              - "22"
              - "33"
        - name: std1
          type: standard
          permit: true
          members:
            route_target:
              - "101.101"
              - "201.201"
            route_origin:
              - "301.301"
              - "401.401"
      state: merged
    register: merge_bgp_extcommunity_single_rerun_output

  - name: Delete a single member of a exp bgp ext community
    sonic_bgp_ext_communities:
      config:
        - name: exp1
          type: expanded
          members:
            regex:
            - "11"
      state: deleted
    register: delete_member_bgp_extcommunity_single_output
  - name: Delete a single member of a exp bgp ext community Idempotent test
    sonic_bgp_ext_communities:
      config:
        - name: exp1
          type: expanded
          members:
            regex: 
            - "11"
      state: deleted
    register: delete_member_bgp_extcommunity_single_rerun_output

  - name: Delete a single member of a std bgp ext community
    sonic_bgp_ext_communities:
      config:
        - name: std1
          type: standard
          members:
            route_target:
            - "101.101"
      state: deleted
    register: delete_member_std_bgp_extcommunity_single_output
  - name: Delete a single member of a std bgp ext community Idempotent test
    sonic_bgp_ext_communities:
      config:
        - name: std1
          type: standard
          members:
            route_target:
            - "101.101"
      state: deleted
    register: delete_member_std_bgp_extcommunity_single_rerun_output  

  - name: Delete all members in a bgp ext community
    sonic_bgp_ext_communities:
      config:
        - name: exp1
          type: expanded
          members:
            regex:
      state: deleted
    register: delete_all_members_bgp_extcommunity_single_output
  - name: Delete all members in a bgp ext community Idempotent test
    sonic_bgp_ext_communities:
      config:
        - name: exp1
          type: expanded
          members:
            regex:
      state: deleted
    register: delete_all_members_bgp_extcommunity_single_rerun_output

  - name: Delete a single bgp ext community
    sonic_bgp_ext_communities:
      config:
        - name: exp1
          type: expanded
          members:
      state: deleted
    register: delete_single_bgp_extcommunity_single_output
  - name: Delete a single bgp ext community Idempotent test
    sonic_bgp_ext_communities:
      config:
        - name: exp1
          type: expanded
          members:
      state: deleted
    register: delete_single_bgp_extcommunity_single_rerun_output
 
  - name: Delete all bgp ext communities
    sonic_bgp_ext_communities:
      config:
      state: deleted
    register: delete_all_bgp_extcommunity_output
  - name: Delete all bgp ext communities Idempotent test
    sonic_bgp_ext_communities:
      config:
      state: deleted
    register: delete_all_bgp_extcommunity_output_rerun_output
