---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
    - name: "Test sonic_interfaces for merged state 01"
      sonic_interfaces:
        config:
          - name: Loopback91