---
- name: "Test SONiC CLI"
  hosts: sonic2 
  gather_facts: no
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
  - name: Delete all SNMP
    sonic_snmp:
      config:
      state: deleted 
    register: delete_all_snmp_output
  - name: Delete all SNMP Idempotent test
    sonic_snmp:
      config:
      state: deleted
    register: delete_all_snmp_rerun_output

  - name: Add one SNMP
    sonic_snmp:
      config:
        - community: "private123"
          access: "ro"
      state: merged
    register: merge_snmp_single_output
  - name: Add SNMP Idempotent test
    sonic_snmp:
      config:
        - community: "private123"
          access: "ro"
      state: merged
    register: merge_snmp_single_rerun_output

  - name: Add many SNMP
    sonic_snmp:
      config:
        - community: "public"
          access: "ro"
        - community: "public123"
          access: "ro"
        - community: "private"
          access: "ro"
      state: merged
    register: merge_snmp_multiple_output 
  - name: Add many SNMP Idempotent test
    sonic_snmp:
      config:
        - community: "public"
          access: "ro"
        - community: "public123"
          access: "ro"
        - community: "private"
          access: "ro"
      state: merged
    register: merge_snmp_multiple_rerun_output

  - name: Delete SNMP
    sonic_snmp:
      config:
        - community: "public123"
          access: "ro"
      state: deleted
    register: deleted_snmp_output
  - name: Delete SNMP Idempotent test
    sonic_snmp:
      config:
        - community: "public123"
          access: "ro"
      state: deleted
    register: deleted_snmp_rerun_output

  - name: Overridden SNMP
    sonic_snmp:
      config:
        - community: "public"
          access: "rw"
      state: overridden
    register: overridden_snmp_output
  - name: Overridden SNMP Idempotent test
    sonic_snmp:
      config:
        - community: "public"
          access: "rw"
      state: overridden
    register: overridden_snmp_rerun_output

  - name: Replace SNMP
    sonic_snmp:
      config:
        - community: "public"
          access: "ro"
      state: replaced
    register: replace_snmp_output
  - name: Replace SNMP Idempotent test
    sonic_snmp:
      config:
        - community: "public"
          access: "ro"
      state: replaced
    register: replace_snmp_rerun_output
