---
- name: "Test SONiC CLI"
  hosts: sonic2 
  gather_facts: no
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
  - name: Add one bgp_community
    sonic_bgp_communities:
      config:
        - name: test
          type: expanded
          permit: true
          members:
            regex:
              - "11"
              - "22"
              - "33"
        - name: test_1
          type: expanded
          permit: true
          members:
            regex:
              - "101.101"
              - "201.201"
              - "301.301"
      state: merged
    register: merge_bgp_community_single_output
  - name: Add one bgp_community Idempotent test
    sonic_bgp_communities:
      config:
        - name: test
          type: expanded
          permit: true
          members:
            regex:
              - "11"
              - "22"
              - "33"
        - name: test_1
          type: expanded
          permit: true
          members:
            regex:
              - "101.101"
              - "201.201"
              - "301.301"
      state: merged
    register: merge_bgp_community_single_rerun_output

  - name: Delete a single member of a bgp community
    sonic_bgp_communities:
      config:
        - name: test_1
          type: expanded
          members:
            regex:
            - "101.101"
      state: deleted
    register: delete_member_bgp_community_single_output
  - name: Delete a single member of a bgp community Idempotent test
    sonic_bgp_communities:
      config:
        - name: test_1
          type: expanded
          members:
            regex: 
            - "101.101"
      state: deleted
    register: delete_member_bgp_community_single_rerun_output

  - name: Delete a single bgp community
    sonic_bgp_communities:
      config:
        - name: test
          type: expanded
          members:
      state: deleted
    register: delete_single_bgp_community_single_output
  - name: Delete a single bgp community Idempotent test
    sonic_bgp_communities:
      config:
        - name: test
          type: expanded
          members:
      state: deleted
    register: delete_single_bgp_community_single_rerun_output

  - name: Delete all members in a bgp community
    sonic_bgp_communities:
      config:
        - name: test_1
          type: expanded
          members:
            regex:
      state: deleted
    register: delete_all_members_bgp_community_single_output
  - name: Delete all members in a bgp community Idempotent test
    sonic_bgp_communities:
      config:
        - name: test_1
          type: expanded
          members:
            regex:
      state: deleted
    register: delete_all_members_bgp_community_single_rerun_output

  - name: Delete all bgp communities
    sonic_bgp_communities:
      config:
      state: deleted
    register: delete_all_bgp_community_output
  - name: Delete all bgp communities Idempotent test
    sonic_bgp_communities:
      config:
      state: deleted
    register: delete_all_bgp_community_output_rerun_output
