---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
    - name: "Test sonic_vxlans merged state"
      sonic_vxlans:
        config:
          - name: vteptest1
            source_ip: 1.1.1.1
            vlanmap: 
              - vni: 101
                vlan: 11
              - vni: 102
                vlan: 12
            vrfmap: 
              - vni: 101
                vrf: Vrfcheck1
              - vni: 102
                vrf: Vrfcheck2
        state: merged
