---
- name: "Test SONiC CLI"
  hosts: datacenter
  gather_facts: no
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
  - name: Delete all VLANs
    sonic_vlans:
      config:
      state: deleted
    register: delete_all_output

  - name: Add VLANs
    sonic_vlans:
      config:
        - vlan_id: 701
        - vlan_id: 702
        - vlan_id: 703
        - vlan_id: 704
      state: merged
    register: merge_vlans_output
  - name: Add VLANs Idempotent test
    sonic_vlans:
      config:
        - vlan_id: 701
        - vlan_id: 702
        - vlan_id: 703
        - vlan_id: 704
      state: merged
    register: merge_vlans_rerun_output
  - name: Delete VLANs
    sonic_vlans:
      config:
        - vlan_id: 701
        - vlan_id: 702
      state: deleted
    register: deleted_vlans_output
  - name: Delete VLANs Idempotent test
    sonic_vlans:
      config:
        - vlan_id: 701
        - vlan_id: 702
      state: deleted
    register: deleted_vlans_rerun_output

  - name: Delete all VLANs
    sonic_vlans:
      config:
      state: deleted
    register: deleted_all_vlans_output
  - name: Delete all VLANs Idempotent test
    sonic_vlans:
      config:
      state: deleted
    register: deleted_all_vlans_rerun_output
