---
- name: "Test SONiC CLI"
  hosts: datacenter 
  gather_facts: no
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
  - name: Test SONiC single command
    sonic_facts:
      gather_network_resources:
        - l3_interfaces
    register: cmd_op
  - debug: var=cmd_op
