---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
    - name: "Test sonic_vrf_interfaces deleted all"
      sonic_vrf_interfaces:
        config:
        state: deleted
      register: deleted_all_01_output

    - name: "Test sonic_vrf_interfaces merged 01"
      sonic_vrf_interfaces:
        config:
          - name: Vrfcheck1
            members:
              - Ethernet64
              - Ethernet60
          - name: Vrfcheck2
            members:
              - Ethernet20
              - Ethernet24
        state: merged
      register: merged_01_output

    - name: "Test sonic_vrf_interfaces merged 02"
      sonic_vrf_interfaces:
        config:
          - name: Vrfcheck1
            members:
              - Ethernet64
              - Ethernet60
          - name: Vrfcheck2
            members:
              - Ethernet20
              - Ethernet24
        state: merged
      register: merged_02_output

    - name: "Test sonic_vrf_interfaces deleted 01"
      sonic_vrf_interfaces:
        config:
          - name: Vrfcheck1
            members:
          - name: Vrfcheck2
            members:
              - Ethernet20
              - Ethernet24
          - name: Vrfcheck3
            members:
              - Ethernet20
              - Ethernet24
          - name: Vrfcheck6
            members:
              - Ethernet20
              - Ethernet24
        state: deleted
      register: deleted_01_output

    - name: "Test sonic_vrf_interfaces deleted 02"
      sonic_vrf_interfaces:
        config:
          - name: Vrfcheck1
            members:
          - name: Vrfcheck2
            members:
              - Ethernet20
              - Ethernet24
          - name: Vrfcheck3
            members:
              - Ethernet20
              - Ethernet24
          - name: Vrfcheck6
            members:
              - Ethernet20
              - Ethernet24
        state: deleted
      register: deleted_02_output

    - name: "Test sonic_vrf_interfaces replaced 01"
      sonic_vrf_interfaces:
        config:
          - name: Vrfcheck1
            members:
              - Ethernet52
              - Ethernet152
          - name: Vrfcheck3
            members:
              - Ethernet12
              - Ethernet28
        state: replaced
      register: replaced_01_output

    - name: "Test sonic_vrf_interfaces replaced 02"
      sonic_vrf_interfaces:
        config:
          - name: Vrfcheck1
            members:
              - Ethernet52
              - Ethernet152
          - name: Vrfcheck3
            members:
              - Ethernet12
              - Ethernet28
        state: replaced
      register: replaced_02_output

    - name: "Test sonic_vrf_interfaces overridden 01"
      sonic_vrf_interfaces:
        config:
          - name: Vrfcheck3
            members:
              - Ethernet52
              - Ethernet152
        state: overridden
      register: overridden_01_output

    - name: "Test sonic_vrf_interfaces overridden 01"
      sonic_vrf_interfaces:
        config:
          - name: Vrfcheck3
            members:
              - Ethernet52
              - Ethernet152
        state: overridden
      register: overridden_02_output

    - name: "Test sonic_vrf_interfaces deleted all 01"
      sonic_vrf_interfaces:
        config:
        state: deleted
      register: deleted_all_02_output

    - name: "Test sonic_vrf_interfaces deleted all 02"
      sonic_vrf_interfaces:
        config:
        state: deleted
      register: deleted_all_03_output
