---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
    - name: "Test sonic_bgp_neighbors_af Delete all 01"
      sonic_bgp_neighbors_af:
        state: deleted

    - name: "Test sonic_bgp_neighbors_af Delete all 02"
      sonic_bgp_neighbors_af:
        state: deleted

    - name: "Test sonic_bgp_neighbors_af merge afi safi 01"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                  - afi: ipv6
                    safi: unicast
        state: merged

    - name: "Test sonic_bgp_neighbors_af merge afi safi 02"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                  - afi: ipv6
                    safi: unicast
        state: merged

    - name: "Test sonic_bgp_neighbors_af merge 01"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 51
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 6
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
              - neighbor: Ethernet228
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      origin: true
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: true
                    route_server_client: true
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 6
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
                  - afi: ipv6
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 6
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
              - neighbor: Ethernet228
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      origin: true
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: true
                    route_server_client: true
                  - afi: ipv6
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 2
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: true
                    route_server_client: true
        state: merged

    - name: "Test sonic_bgp_neighbors_af merge 02"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 51
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 6
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
              - neighbor: Ethernet228
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      origin: true
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: true
                    route_server_client: true
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 6
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
                  - afi: ipv6
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 6
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
              - neighbor: Ethernet228
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      origin: true
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: true
                    route_server_client: true
                  - afi: ipv6
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 2
                    route_map:
                      - name: aa
                        direction: out
                      - name: bb
                        direction: in
                    route_reflector_client: true
                    route_server_client: true
        state: merged

    - name: "Test sonic_bgp_neighbors_af merge specific values 01"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: false
                    allowas_in:
                      origin: true
                    route_map:
                      - name: bb
                        direction: out
                      - name: aa
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
              - neighbor: Ethernet228
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 4
                    route_map:
                      - name: bb
                        direction: out
                      - name: aa
                        direction: in
                    route_reflector_client: true
                    route_server_client: false
        state: merged

    - name: "Test sonic_bgp_neighbors_af merge specific values 02"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: false
                    allowas_in:
                      origin: true
                    route_map:
                      - name: bb
                        direction: out
                      - name: aa
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
              - neighbor: Ethernet228
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      value: 4
                    route_map:
                      - name: bb
                        direction: out
                      - name: aa
                        direction: in
                    route_reflector_client: true
                    route_server_client: false
        state: merged

    - name: "Test sonic_bgp_neighbors_af delete specific values 01"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: false
                    allowas_in:
                      value: 5
                    route_map:
                      - name: bb
                        direction: out
                      - name: aa
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
              - neighbor: Ethernet228
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      origin: true
                    route_map:
                      - name: bb
                        direction: out
                      - name: aa
                        direction: in
                    route_reflector_client: true
                    route_server_client: false
        state: deleted

    - name: "Test sonic_bgp_neighbors_af delete specific values 02"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: false
                    allowas_in:
                      value: 5
                    route_map:
                      - name: bb
                        direction: out
                      - name: aa
                        direction: in
                    route_reflector_client: false
                    route_server_client: true
              - neighbor: Ethernet228
                address_family:
                  - afi: ipv4
                    safi: unicast
                    activate: true
                    allowas_in:
                      origin: true
                    route_map:
                      - name: bb
                        direction: out
                      - name: aa
                        direction: in
                    route_reflector_client: true
                    route_server_client: false
        state: deleted

    - name: "Test sonic_bgp_neighbors_af delete specific address family 01"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
        state: deleted

    - name: "Test sonic_bgp_neighbors_af delete specific address family 02"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
                address_family:
                  - afi: ipv4
                    safi: unicast
        state: deleted

    - name: "Test sonic_bgp_neighbors_af delete all address family of specific neighbor 01"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
        state: deleted

    - name: "Test sonic_bgp_neighbors_af delete all address family of specific neighbor 02"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
            neighbors:
              - neighbor: Ethernet224
        state: deleted

    - name: "Test sonic_bgp_neighbors_af delete all neighbors address family of specific bgp 01"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
        state: deleted

    - name: "Test sonic_bgp_neighbors_af delete all neighbors address family of specific bgp 02"
      sonic_bgp_neighbors_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
        state: deleted

    - name: "Test sonic_bgp_neighbors_af Delete all 03"
      sonic_bgp_neighbors_af:
        state: deleted

    - name: "Test sonic_bgp_neighbors_af Delete all 04"
      sonic_bgp_neighbors_af:
        state: deleted
