namespace: dellemc
name: sonic
version: 0.0.1-dev2
readme: README.md
authors:
- Senthil Kumar Ganesan <Senthil_Kumar_Ganesa@Dell.com>
- Abirami <Abirami_N@Dell.com>
- Dhivya <Dhivya_P@Dell.com>
- Mohamed Javeed <Mohamed_Javeed_Faroo@Dell.com>
- Nirai Madai <Niraimadaiselvam_Mar@Dell.com>
 
description: The Ansible collection for Dell EMC Open Networking Powered by SONiC 
license_file: LICENSE 
tags: [dellemc, dell, networking, onos, nos, sonic]
dependencies: 
  "ansible.netcommon": "*"
repository: https://github.com/ansible-collections/dellemc.sonic 
documentation: https://ansible-dellos-docs.readthedocs.io
issues: https://github.com/ansible-collections/dellemc.sonic/issues 
