namespace: dellemc_networking
name: sonic
version: 0.0.5
readme: README.rst
authors:
- Senthil Kumar Ganesan <Senthil_Kumar_Ganesa@Dell.com>
- Abirami <Abirami_N@Dell.com>
- Dhivya <Dhivya_P@Dell.com>
- Mohamed Javeed <Mohamed_Javeed_Faroo@Dell.com>
 
description: The Ansible collection for Dell EMC Open Networking Powered by SONiC 
license:
- GPL-2.0-or-later
license_file: LICENSE 
tags: [dellemc, dell, networking, onos, nos, sonic]
dependencies: 
  "ansible.netcommon": "*"
repository: https://github.com/ansible-collections/dellemc_networking.sonic 
documentation: https://ansible-dellos-docs.readthedocs.io 
issues: https://github.com/ansible-collections/dellemc_networking.sonic/issues 
